<a href="https://colab.research.google.com/github/Ebuka-1/Ebuka-1/blob/main/Ebuka.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = [6,7,8,9]
print(type(arr))

<class 'list'>


In [ ]:
a = np.array(arr)
print(a)

[6 7 8 9]


In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
np.random.random((2, 3))

array([[0.31991406, 0.4162931 , 0.66029799],
       [0.57040431, 0.82954418, 0.77278169]])

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
b[0, 0]

1

In [ ]:
b[3, 5]

IndexError: ignored

In [ ]:
d = np.array([4, 5, 6],[9, 8, 7])

NameError: ignored

In [ ]:
import numpy as np
d = np.array([4, 5, 6],[9, 8, 7])

TypeError: ignored

In [ ]:
d = np.array([4, 5, 6],[9, 8, 7])
print(d)

TypeError: ignored

In [ ]:
d = np.array([[4.0, 5.0, 6.0],[9.0, 8.0, 7.0]])
d[1, 0:2]

array([9., 8.])

In [ ]:
d[1, 0:3]

array([9., 8., 7.])

In [ ]:
np.where(d == 8)

(array([1]), array([1]))

In [ ]:
np.zeros(3)

NameError: ignored

In [ ]:
import numpy as np
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros(2, 3)

TypeError: ignored

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
d = np.array([4.0, 5.0, 6.0],[9.0, 8.0, 7.0])

TypeError: ignored

In [ ]:
url = 'https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv?raw=true'
df = pd.read_csv(url, error_bad_lines = False)

NameError: ignored

In [ ]:
import pandas as pd

In [ ]:
url = 'https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv?raw=true'

In [ ]:
df = pd.read_csv(url, error_bad_lines = False)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)


In [ ]:
df.describe(include="all")

record_id  utility_id_ferc1   report_year  \
count                   29523      29523.000000  29523.000000   
unique                  29523               NaN           NaN   
top     f1_fuel_1994_12_1_0_7               NaN           NaN   
freq                        1               NaN           NaN   
mean                      NaN        118.601836   2005.806050   
std                       NaN         74.178353      7.025483   
min                       NaN          1.000000   1994.000000   
25%                       NaN         55.000000   2000.000000   
50%                       NaN        122.000000   2006.000000   
75%                       NaN        176.000000   2012.000000   
max                       NaN        514.000000   2018.000000   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
count             29523               29523     29343     2.952300e+04   
unique             2315                   6         9              NaN   
top           big stone                 gas       mcf              NaN   
freq                156               11486     11354              NaN   
mean                NaN                 NaN       NaN     2.622119e+06   
std                 NaN                 NaN       NaN     9.118004e+06   
min                 NaN                 NaN       NaN     1.000000e+00   
25%                 NaN                 NaN       NaN     1.381700e+04   
50%                 NaN                 NaN       NaN     2.533220e+05   
75%                 NaN                 NaN       NaN     1.424034e+06   
max                 NaN                 NaN       NaN     5.558942e+08   

        fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
count          29523.000000               29523.000000   
unique                  NaN                        NaN   
top                     NaN                        NaN   
freq                    NaN                        NaN   
mean               8.492111                 208.649031   
std               10.600220                2854.490090   
min                0.000001                -276.080000   
25%                1.024000                   5.207000   
50%                5.762694                  26.000000   
75%               17.006000                  47.113000   
max              341.260000              139358.000000   

        fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
count                   2.952300e+04         29523.000000  
unique                           NaN                  NaN  
top                              NaN                  NaN  
freq                             NaN                  NaN  
mean                    9.175704e+02            19.304354  
std                     6.877593e+04          2091.540939  
min                    -8.749370e+02           -41.501000  
25%                     3.778500e+00             1.940000  
50%                     1.737100e+01             4.127000  
75%                     4.213700e+01             7.745000  
max                     7.964521e+06        359278.000000

In [ ]:
df.is_null().sum()

AttributeError: ignored

In [ ]:
df.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [ ]:
df.groupby(fuel_unit)[fuel_unit].count()

NameError: ignored

In [ ]:
df.groupby('fuel_unit')['fuel_unit'].sum()

fuel_unit
bbl       bblbblbblbblbblbblbblbblbblbblbblbblbblbblbblb...
gal       galgalgalgalgalgalgalgalgalgalgalgalgalgalgalg...
gramsU    gramsUgramsUgramsUgramsUgramsUgramsUgramsUgram...
kgU       kgUkgUkgUkgUkgUkgUkgUkgUkgUkgUkgUkgUkgUkgUkgUk...
mcf       mcfmcfmcfmcfmcfmcfmcfmcfmcfmcfmcfmcfmcfmcfmcfm...
mmbtu     mmbtummbtummbtummbtummbtummbtummbtummbtummbtum...
mwdth     mwdthmwdthmwdthmwdthmwdthmwdthmwdthmwdthmwdthm...
mwhth     mwhthmwhthmwhthmwhthmwhthmwhthmwhthmwhthmwhthm...
ton       tontontontontontontontontontontontontontontont...
Name: fuel_unit, dtype: object

In [ ]:
df[["fuel_unit"]]=df[["fuel_unit"]].fillna(value="mcf")

In [ ]:
df["fuel_unit"].isnull().count()

29523